### ISSUE TITLE
Make roads visible/movable

### ISSUE THREAD

**Issue by WulfgarCA** [sacah/foe-city-layout#4]
Sorry to bother you again.
Is it a lot of work to show the roads as well and make them moveable?
At the moment I only see the building and i cant distinguish between roads and empty fields.

Thanks and have a great day!

**Comment by sacah** [comment]
When I loop over the buildings during an import, I remove any that have a type of STREET, this is because if you wanted to move/remove the roads, you'd have to do it 1x1 square at a time. And if you wanted to add roads, you'd need to add them 1x1 square at a time via the dropdown and Add button. 
I use this tool to do fairly major reshuffles, so dealing with roads would be very annoying for me every time, and my cities are pretty much set up as a grid, so it's easy enough to distinguish what's a road.

I couldn't think of any quick and clean ways to overcome those issues, and roads are very low importance for me, so I haven't given it much thought. I'll leave this open and change it to a Feature Request and if others would like the feature too I can spend some time adding it in.
